services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        container_name: st-app
        working_dir: /var/www/html
        ports:
            - "80:8080"
        depends_on:
            - mysql
            - redis
        environment:
            DB_HOST: mysql
            REDIS_HOST: redis
        networks:
            - WebFPTE

    mysql:
        image: mysql:8.0
        container_name: st-mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: simple_website
        volumes:
            - mysql_data:/var/lib/mysql
        ports:
            - "3311:3306"
        networks:
            - WebFPTE

    redis:
        image: redis:alpine
        container_name: st-redis
        restart: always
        volumes:
            - redis_data:/data
        networks:
            - WebFPTE

volumes:
    mysql_data:
    redis_data:

networks:
    WebFPTE:
        driver: bridge
